server:
  port: 8080

spring.data.mongodb.host: 127.0.0.1
spring.data.mongodb.port: 27017
spring.datasource.driverClassName: com.mongodb.Mongo
spring.data.mongodb.database: productDigitalDiary
spring.data.mongodb.repositories.enabled: true
